$(function(){
  $("#item_menu").click(function(){
    $("#sub_menu").slideToggle(300);
  });
});
$(function(){
  $("#sub_menu").click(function(){
    $("#sub_menu").slideToggle(300);
  });
});
$(function(){
  $("#item_menu1").click(function(){
    $("#sub_menu1").slideToggle(300);
  });
});
$(function(){
  $("#sub_menu1").click(function(){
    $("#sub_menu1").slideToggle(300);
  });
});
